# Generated by Django 3.2.6 on 2021-08-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_post_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='garnish',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
